Feat/RSS-ECOMM-2_01: Implement client-side validation for login form
Maksim99745/eCommerce-Application pull request #73
Opened 2024-05-08 19:23 UTC by Tetiana-KET

RSS-ECOMM-2_01: Implement client-side validation for login form
resolve #58, resolve #59

#### 🤔 This is a ...

- [x] 🌟 New task

#### Description

Implement client-side validation for the login form, including email 📧 and password 🔑 fields. 
Ensure that input validation checks are performed in real-time when the user enters their information.

**Email Validation Rules** 📏
- [x] Describe tests for Email Validation 
- [x] Email address must be properly formatted (e.g., [user@example.com](mailto:user@example.com)).
- [x] Email address must not contain leading or trailing whitespace.
- [x] Email address must contain a domain name (e.g., example.com).
- [x] Email address must contain an '@' symbol separating local part and domain name.
**Password Validation Rul** 📏
- [x] Describe tests for Password Validation 
- [x] Password must be at least 8 characters long.
- [x] Password must contain at least one uppercase letter (A-Z).
- [x] Password must contain at least one lowercase letter (a-z).
- [x] Password must contain at least one digit (0-9).
- [x] Password must contain at least one special character (e.g., !@#$%^&*).
- [x] Password must not contain leading or trailing whitespace.
**Show/Hide Password Functionality** 👁️‍🗨️
- [x] Provide a button or a checkbox to allow users to toggle the visibility of their password.
- [x] When this option is activated, users should be able to see their password in plaintext.
- [x] When this option is deactivated, the password should be replaced with asterisks or bullet points.
**Acceptance Criteria** ✅
- [x] Email field validation checks for a properly formatted email address according to the specified rules.
- [x] Password field validation checks for meeting the length and complexity requirements.
- [x] Show/hide password functionality allows users to toggle password visibility.
- [x] Validation checks are performed as the user types.

#### Checklist

- [x] ✅ I have performed a self-review of my own code.
- [x] 📝 I have commented my code, particularly in hard-to-understand areas.
- [x] 🔧 I have made corresponding changes to the documentation (if applicable).
- [x] 🚫 My changes generate no new warnings or errors.
- [x] 👌 Have at least 1 approve.
- [x] 🌳 Branch from `develop`/`release/...` and target to `develop`/`release/...`.

2024-05-08 20:00 UTC, JsPowWow commented on package.json
> +    "react": "^17.0.0 || ^18.0.0",
Revert this two lines as it was before

2024-05-08 20:12 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +    .max(MAX_LENGTH, 'Password should not be more, then 20 characters')
Not 8, but `...${MIN_LENGTN}...`
Not 20, but `...${MAX_LENGTN}...`
Use Your constants in messages

2024-05-08 20:14 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +  'Passwords must consist only of Latin letters (A-Z, a-z), be 8 - 20 characters and contain at least: one uppercase letter (A-Z), one lowercase letter (a-z), one digit (0-9) and one special characte
Not 8, but `...${MIN_LENGTN}...`
Not 20, but `...${MAX_LENGTN}...`
Use Your constants in messages

2024-05-09 10:43 UTC, Tetiana-KET commented on src/pages/Login/schema.ts
> +    .max(MAX_LENGTH, 'Password should not be more, then 20 characters')
done, thank you

2024-05-09 15:33 UTC, JsPowWow requested changes

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +const passwordValidationRegEx = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*])[A-Za-z\d!@#$%^&*]{8,20}$/;
```suggestion
const TEST_PASSWORD_REG_EX = /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d)(?=.*[!@#$%^&*])[A-Za-z\d!@#$%^&*]{8,20}$/;
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +});
```suggestion
    .regex(TEST_PASSWORD_REG_EX, 'Invalid password'),
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return true if password is valid', () => {
```suggestion
  test('password should be valid', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password contains not only Latin letters', () => {
```suggestion
  test('password must consist only of Latin letters (A-Z, a-z)', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password contains whitespace', () => {
```suggestion
  test('password should not contains whitespace', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password contains trailing whitespace', () => {
```suggestion
  test('password should not contains trailing whitespace', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password contains leading whitespace', () => {
```suggestion
  test('password must not contain leading whitespace', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password does not contain special character', () => {
```suggestion
  test('password must contain at least one special character', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password does not contain digits', () => {
```suggestion
  test('password must contain at least one digit', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password does not contain letters', () => {
```suggestion
  test('password must contain at least one uppercase & lowercase Latin letters', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password does not contain at least one lowercase letter', () => {
```suggestion
  test('Password must contain at least one lowercase Latin letter', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password does not contain at least one uppercase letter', () => {
```suggestion
  test('password must contain at least one uppercase letter', () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test(`should return false if password length is more then ${MAX_LENGTH}`, () => {
```suggestion
  test(`password length should not be more, then 20 characters`, () => {
```

2024-05-09 15:33 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test(`should return false if password length is less them ${MIN_LENGTH}`, () => {
```suggestion
  test(`password length must be at least 8 characters long`, () => {
```

2024-05-09 15:41 UTC, JsPowWow requested changes

2024-05-09 15:41 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if password is empty', () => {
```suggestion
  test('password must not be empty', () => {
```

2024-05-09 15:41 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return true when email is valid', () => {
```suggestion
  test('email should be valid', () => {
```

2024-05-09 15:41 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return true when email contains "."', () => {
```suggestion
  test('email with "." should be valid', () => {
```

2024-05-09 15:41 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return true when email contains "-"', () => {
```suggestion
  test('email with "-" should be valid', () => {
```

2024-05-09 15:41 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return true when email contains "_"', () => {
```suggestion
  test('email with "_" should be valid', () => {
```

2024-05-09 15:41 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if email contains trailing whitespace', () => {
```suggestion
  test('email should not contains trailing whitespace', () => {
```

2024-05-09 15:49 UTC, JsPowWow requested changes

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if email contains leading whitespace', () => {
```suggestion
  test('email should not contain leading whitespace', () => {
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if email does not contain "@"', () => {
```suggestion
  test('email should contain "@"', () => {
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if email does not contain a domain name', () => {
```suggestion
  test('email should contain a domain name', () => {
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if email is not properly formatted', () => {
```suggestion
  test('email address must be properly formatted and contain a domain name', () => {
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +  test('should return false if email is an empty string', () => {
```suggestion
  test('email address must not be empty', () => {
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +describe('email validation', () => {
```suggestion
describe('email address validation tests', () => {
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/Login.test.tsx
> +test('should return false if receives an empty object', () => {
```suggestion
test('email address should be provided', () => {
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +    .regex(/^[^\s]+$/, 'Passwords must not contain whitespaces')
```suggestion
    .regex(/^[^\s]+$/, 'Password must not contain whitespaces')
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +    .regex(/(?=.*[a-z])(?=.*[A-Z])/, 'Passwords must contain uppercase and lowercase Latin letters (A-Z, a-z)')
```suggestion
    .regex(/(?=.*[a-z])(?=.*[A-Z])/, 'Password must contain uppercase and lowercase Latin letters (A-Z, a-z)')
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +    .regex(/(?=.*\d)/, 'Passwords must contain at least one digit (0-9)')
```suggestion
    .regex(/(?=.*\d)/, 'Password must contain at least one digit (0-9)')
```

2024-05-09 15:49 UTC, JsPowWow commented on src/pages/Login/schema.ts
> +    .regex(/(?=.*[!@#$%^&])/, 'Passwords must contain at least one special character (!@#$%^&)')
```suggestion
    .regex(/(?=.*[!@#$%^&])/, 'Password must contain at least one special character (!@#$%^&)')
```

2024-05-09 18:59 UTC, Tetiana-KET commented on src/pages/Login/schema.ts
> +});
are you sure i should replace line 18 - }); with - .regex(TEST_PASSWORD_REG_EX, 'Invalid password'),

2024-05-09 19:01 UTC, Tetiana-KET commented on src/pages/Login/schema.ts
> +});
replace line 17 in IDE

2024-05-12 16:48 UTC, JsPowWow approved these changes

2024-05-13 09:33 UTC, JsPowWow approved these changes

2024-05-13 09:35 UTC, merged